export const GET_POSTS = 'GET_POSTS'
export const SET_SINGLE = 'SET_SINGLE'
export const SET_BACKGROUND = 'SET_BACKGROUND'
export const SET_PROJECT = 'SET_PROJECT'
export const SHOW_DATES = 'SHOW_DATES'
export const SET_EVENTS = 'SET_EVENTS'
